version: '3'
services:
  simple:
    build: 
      context: .
      dockerfile: simple.Dockerfile
    ports:
      - 80:80
  route:
    build:
      context: .
      dockerfile: router.Dockerfile
    ports:
      - 80:80
  oss:
    build:
      context: .
      dockerfile: oss.Dockerfile
      args:
        - ACCESS_KEY_ID
        - ACCESS_KEY_SECRET
        - ENDPOINT=oss-cn-beijing.aliyuncs.com
    ports:
      - 80:80
